### ISSUE TITLE
It is not a issue but a question

### ISSUE THREAD

**Issue by watershade** [karlnicholas/aws_shadow_i2s_CC3220S_LAUNCHXL_tirtos_ccs#1]
I find you have configured aws_iot_config.h but not cert.h to register cert. But I do know where to put those three files in . A folder named "cert" under project path?

**Comment by karlnicholas** [comment]
I put the certificate files from AWS in the /cert directory of the CC3220S fatfs file system, so they are not part of the project. This is defined in `aws_iot_config.h` in lines 31-33. This references a fatfs directory on the device's file system. You can either put them in the `certs.h` and define `OVERWRITE_CERTS` in the `main_rtos.c` so that the application flashes them for you (should remove the changes after it flashed once so the application doesn't keep flashing the file system every time it runs), or you can flash them there with the UniFlash program. What's important is using UniFlash to write the real certcatalog to the `CC3320S` device so that the `root-ca` certificate from AWS can be authenticated. See E2E at [CC3220S-LAUNCHXL: SimpleLink Secure Socket Connection Failure](https://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/t/643208).

**Comment by watershade** [comment]
Thanks very much.
